In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df=pd.read_csv(r"C:\Users\HP\cardio_train.csv" ,sep=';' )
df=df.drop(['id'],axis=1)
df

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    140     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
69995  19240       2     168    76.0    120     80            1     1      1   
69996  22601       1     158   126.0    140     90            2     2      0   
69997  19066       2     183   105.0    180     90            3     1      0   
69998  22431       1     163    72.0    135     80            1     2      0   
69999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  cardio  
0         0       1       0  
1         0       1       1  
2         0       0       1  
3         0       1       1  
4         0       0       0  
...     ...     ...     ...  
69995     0       1       0  
69996     0       1       1  
69997     1       0       1  
69998     0       0       1  
69999     0       1       0  

[70000 rows x 12 columns]

# splitting dataset into x and y

In [3]:
x=df.iloc[:,0:11]
x

age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  smoke  \
0      18393       2     168    62.0    110     80            1     1      0   
1      20228       1     156    85.0    140     90            3     1      0   
2      18857       1     165    64.0    130     70            3     1      0   
3      17623       2     169    82.0    150    100            1     1      0   
4      17474       1     156    56.0    100     60            1     1      0   
...      ...     ...     ...     ...    ...    ...          ...   ...    ...   
69995  19240       2     168    76.0    120     80            1     1      1   
69996  22601       1     158   126.0    140     90            2     2      0   
69997  19066       2     183   105.0    180     90            3     1      0   
69998  22431       1     163    72.0    135     80            1     2      0   
69999  20540       1     170    72.0    120     80            2     1      0   

       alco  active  
0         0       1  
1         0       1  
2         0       0  
3         0       1  
4         0       0  
...     ...     ...  
69995     0       1  
69996     0       1  
69997     1       0  
69998     0       0  
69999     0       1  

[70000 rows x 11 columns]

In [5]:
y=df.iloc[:,11:]  
y

cardio
0           0
1           1
2           1
3           1
4           0
...       ...
69995       0
69996       1
69997       1
69998       1
69999       0

[70000 rows x 1 columns]

In [30]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

# 1.Logistic Regression(71.5% Accuracy)

In [44]:
from sklearn.linear_model import LogisticRegression
model1=LogisticRegression()
model1.fit(xtrain,ytrain)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [40]:
ans1=model1.predict(xtest)
ans1

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [46]:
model1.score(xtest,ytest)

0.715

# 2.SVM(60.2% Accuracy)

In [72]:
from sklearn.svm import SVC
model2=SVC()
model2.fit(xtrain,ytrain)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [74]:
ans2=model2.predict(xtest)
ans2

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [76]:
model2.score(xtest,ytest)

0.6019285714285715

# 3.Decision Tree Classifier(63.5% Accuracy)

In [78]:
from sklearn.tree import DecisionTreeClassifier
model3=DecisionTreeClassifier()
model3.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [80]:
ans3=model3.predict(xtest)
ans3

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [82]:
model3.score(xtest,ytest)

0.6350714285714286

# 4.Random Forest Classifier(71.9% - Highest Accuracy)

In [84]:
from sklearn.ensemble import RandomForestClassifier
model4=RandomForestClassifier()
model4.fit(xtrain,ytrain)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [87]:
ans4=model4.predict(xtest)
ans4

array([0, 0, 1, ..., 0, 0, 1], dtype=int64)

In [89]:
model4.score(xtest,ytest)

0.7187142857142857

# 5.Naive Bayes Classifier(59.7% Accuracy)

In [94]:
from sklearn.naive_bayes import GaussianNB
model5=GaussianNB()
model5.fit(xtrain,ytrain)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [96]:
ans5=model5.predict(xtest)
ans5

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [98]:
model5.score(xtest,ytest)

0.5968571428571429

 # 6.KNN Classifier(68.8% Accuracy)

In [101]:
from sklearn.neighbors import KNeighborsClassifier
model6=KNeighborsClassifier(n_neighbors=5)
model6.fit(xtrain,ytrain)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [103]:
ans6=model6.predict(xtest)
ans6

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [105]:
model6.score(xtest,ytest)

0.6880714285714286